/**
 * Metadata landmark miniatur Kota Palembang.
 * `pos` = titik pusat landmark pada grid diorama (x, z), `focus` = jarak orbit kamera.
 */
export const LANDMARKS = [
  {
    id: 'ampera',
    name: 'Jembatan Ampera',
    short: 'Ikon Kota',
    color: '#d7382c',
    pos: [0, 0],
    labelY: 22,
    focus: { radius: 92, phi: 1.04, theta: -0.55 },
    kicker: 'Landmark Utama',
    desc: 'Jembatan merah yang membentang di atas Sungai Musi dan menghubungkan Seberang Ilir dengan Seberang Ulu. Dua menara kembarnya dulu berfungsi mengangkat bagian tengah jembatan agar kapal besar dapat lewat.',
    meta: [
      ['Dibangun', '1962 – 1965'],
      ['Panjang', '± 1.117 m'],
      ['Menara', '2 × ± 63 m'],
      ['Arti nama', 'Amanat Penderitaan Rakyat'],
    ],
  },
  {
    id: 'masjid',
    name: 'Masjid Agung SMB II',
    short: 'Wisata Religi',
    color: '#128a72',
    pos: [-115, -82],
    labelY: 21,
    focus: { radius: 68, phi: 1.00, theta: -2.45 },
    kicker: 'Cagar Budaya',
    desc: 'Masjid Agung Sultan Mahmud Badaruddin II, masjid terbesar di Palembang. Atap limas bersusun dengan ujung melengkung khas Nusantara berpadu menara bergaya Tiongkok dan ornamen Timur Tengah.',
    meta: [
      ['Diresmikan', '26 Mei 1748'],
      ['Pendiri', 'Sultan Mahmud Badaruddin I'],
      ['Gaya', 'Melayu · Tionghoa · Eropa'],
      ['Kapasitas', '± 15.000 jemaah'],
    ],
  },
  {
    id: 'benteng',
    name: 'Benteng Kuto Besak',
    short: 'Situs Sejarah',
    color: '#9a7b52',
    pos: [-45, -70],
    labelY: 14,
    focus: { radius: 66, phi: 1.06, theta: -1.35 },
    kicker: 'Peninggalan Kesultanan',
    desc: 'Benteng batu bata peninggalan Kesultanan Palembang Darussalam yang menghadap langsung ke Sungai Musi. Empat sudutnya berupa bastion tempat meriam pertahanan; pelatarannya kini jadi alun-alun tepi sungai.',
    meta: [
      ['Dibangun', '1780 – 1797'],
      ['Diresmikan', '23 Februari 1790'],
      ['Ukuran', '288,75 × 183,75 m'],
      ['Tinggi dinding', '± 9,9 m'],
    ],
  },
  {
    id: 'monpera',
    name: 'Monpera',
    short: 'Monumen',
    color: '#c0c6c9',
    pos: [40, -72],
    labelY: 21,
    focus: { radius: 54, phi: 0.96, theta: 0.85 },
    kicker: 'Monumen Perjuangan',
    desc: 'Monumen Perjuangan Rakyat, berbentuk kelopak bunga melati raksasa yang merekah. Mengenang Pertempuran Lima Hari Lima Malam tahun 1947 melawan tentara Belanda di Palembang.',
    meta: [
      ['Dibangun', '1975 – 1988'],
      ['Bentuk', 'Kelopak melati'],
      ['Lantai', '5 tingkat'],
      ['Peringatan', 'Pertempuran 5 Hari 5 Malam'],
    ],
  },
  {
    id: 'kemaro',
    name: 'Pulau Kemaro',
    short: 'Pagoda 9 Lantai',
    color: '#e0574f',
    pos: [88, 20],
    labelY: 30,
    focus: { radius: 64, phi: 0.98, theta: 0.45 },
    kicker: 'Delta Sungai Musi',
    desc: 'Delta kecil di tengah Sungai Musi dengan pagoda sembilan lantai dan Klenteng Hok Tjing Rio. Terkenal lewat legenda cinta Siti Fatimah dan Tan Bun An, serta perayaan Cap Go Meh setiap tahun.',
    meta: [
      ['Pagoda', '9 lantai'],
      ['Klenteng', 'Hok Tjing Rio'],
      ['Legenda', 'Siti Fatimah & Tan Bun An'],
      ['Perayaan', 'Cap Go Meh'],
    ],
  },
  {
    id: 'limas',
    name: 'Kampung Rumah Limas',
    short: 'Rumah Adat',
    color: '#8a5a34',
    pos: [40, 72],
    labelY: 14,
    focus: { radius: 52, phi: 1.02, theta: 1.15 },
    kicker: 'Arsitektur Tradisional',
    desc: 'Permukiman Seberang Ulu dengan Rumah Limas — rumah panggung kayu unglen dan tembesu berlantai bertingkat (kekijing). Setiap tingkat menandai derajat tamu dalam adat Palembang.',
    meta: [
      ['Tipe', 'Rumah panggung'],
      ['Kayu', 'Unglen · Tembesu'],
      ['Kekijing', '5 tingkat lantai'],
      ['Atap', 'Limas bersusun'],
    ],
  },
  {
    id: 'rakit',
    name: 'Rumah Rakit & Ketek',
    short: 'Hunian Terapung',
    color: '#4c8fa8',
    pos: [-14, 17],
    labelY: 10,
    focus: { radius: 44, phi: 1.12, theta: 0.1 },
    kicker: 'Kehidupan Sungai',
    desc: 'Rumah rakit terapung di atas rangkaian bambu, hunian tertua di tepian Musi. Di antaranya hilir mudik perahu ketek, transportasi tradisional penyeberangan warga Ilir–Ulu.',
    meta: [
      ['Pengapung', 'Bambu & drum'],
      ['Lokasi', 'Tepian Sungai Musi'],
      ['Transportasi', 'Perahu ketek'],
      ['Fungsi', 'Hunian & warung'],
    ],
  },
  {
    id: 'alquran',
    name: 'Al-Qur\u2019an Al-Akbar',
    short: 'Al-Qur\u2019an Raksasa',
    color: '#b8912f',
    pos: [-60, 34],
    labelY: 17,
    focus: { radius: 50, phi: 1.00, theta: -0.9 },
    kicker: 'Wisata Religi',
    desc: 'Museum Al-Qur\u2019an Al-Akbar menyimpan mushaf raksasa berukir pada lembaran kayu tembesu. Ukiran khas Palembang berwarna emas menghiasi 30 juz yang berdiri setinggi bangunan.',
    meta: [
      ['Pengerjaan', '2002 – 2008'],
      ['Bahan', 'Kayu tembesu'],
      ['Lembar', '315 lembar ukir'],
      ['Tinggi', '± 15 m'],
    ],
  },
  {
    id: 'kota',
    name: 'Pusat Kota Ilir',
    short: 'Kawasan Niaga',
    color: '#6d7f8a',
    pos: [-15, -135],
    labelY: 34,
    focus: { radius: 78, phi: 0.94, theta: -3.05 },
    kicker: 'Kawasan Modern',
    desc: 'Kawasan niaga Seberang Ilir di sekitar Pasar 16 Ilir: perkantoran, hotel, dan pusat perbelanjaan yang membentuk siluet kota modern Palembang di balik tepian Musi.',
    meta: [
      ['Kawasan', 'Seberang Ilir'],
      ['Pasar', '16 Ilir'],
      ['Fungsi', 'Niaga & perkantoran'],
      ['Ciri', 'Siluet kota modern'],
    ],
  },
];

export const TIME_PRESETS = {
  pagi: {
    label: 'Pagi',
    sky: ['#6fb3dd', '#b8dcee', '#eaf0e8'],
    fog: '#d6e8ef',
    fogDensity: 0.0011,
    sun: { color: '#fff5e2', intensity: 2.5, pos: [90, 120, 70] },
    hemi: { sky: '#cfe9f5', ground: '#8d7d63', intensity: 1.15 },
    ambient: 0.5,
    water: { deep: '#6d5a3a', shallow: '#a98e5c', sun: 0.5 },
    exposure: 1.0,
    lightsOn: 0,
  },
  senja: {
    label: 'Senja',
    sky: ['#23405f', '#d9764f', '#ffcf94'],
    fog: '#c98f74',
    fogDensity: 0.0015,
    sun: { color: '#ff9a52', intensity: 2.6, pos: [-130, 42, 30] },
    hemi: { sky: '#e8a583', ground: '#4a3524', intensity: 0.72 },
    ambient: 0.34,
    water: { deep: '#4a3524', shallow: '#b8794a', sun: 1.0 },
    exposure: 1.0,
    lightsOn: 0.55,
  },
  malam: {
    label: 'Malam',
    sky: ['#050c16', '#0d1c2e', '#1b3148'],
    fog: '#0a141f',
    fogDensity: 0.0020,
    sun: { color: '#9fc0e8', intensity: 0.35, pos: [-70, 90, -80] },
    hemi: { sky: '#1e3350', ground: '#0a1018', intensity: 0.4 },
    ambient: 0.22,
    water: { deep: '#07111b', shallow: '#14303f', sun: 0.25 },
    exposure: 1.12,
    lightsOn: 1,
  },
};
